apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4eez
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-4eez@sha256:306f22cb13d4b877b75d9656c9ae876767163c728e86c3d2464de75cba73efd0
        name: my-nodejs
        resources: {}
status: {}
