apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-4eez
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-4eez
    app.kubernetes.io/part-of: tkrw-pr712-0075-0071-app
  name: devfile-sample-4eez
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-4eez
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-4eez
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-4eez@sha256:306f22cb13d4b877b75d9656c9ae876767163c728e86c3d2464de75cba73efd0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
